import { makeStyles } from '@mui/styles';

export default makeStyles({
    tow: {
        position: 'absolute',
        height: '80%',
        width: '85%',
        top: '10%',
        left: '9%',
        display: 'flex',
        flexDirection: 'column',
        backgroundColor: '#3A3343',
        animation: 'ease-in fadeIn 250ms',
    },
    towContainer: {
        padding: '2rem',
        height: '100%',
        overflow: 'scroll',
    },
    towHeading: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        borderBottom: '2 solid #6360FF',
    },
    towTabSection: {
        width: '100%',
        border: 50,
        display: 'flex',
        justifyContent: 'left',
    },
    towTabBtn: {
        color: '#fff !important',
        position: 'relative',
        marginRight: '1rem !important',
        padding: '10px 2.5rem !important',
        borderRadius: 5,
        background: '#4C4258 !important',
        transition: 'ease-in 200ms !important',
        fontSize: 11,
        fontWeight: 500,
        boxShadow: 'none !important',
        border: '1px solid #232426 !important',
        '&:hover': {
            color: '#fff !important',
            cursor: 'pointer !important',
            boxShadow: 'none !important',
            backgroundColor: '#4C4258 !important',
        },
    },
    icon: {
        marginRight: '0.35rem',
    },
    towActiveBtn: {
        position: 'relative',
        marginRight: '1rem !important',
        padding: '10px 2.5rem !important',
        borderRadius: 5,
        transition: 'ease-in 200ms !important',
        fontSize: 11,
        fontWeight: 500,
        boxShadow: 'none !important',
        color: '#fff !important',
        cursor: 'pointer !important',
        backgroundColor: '#4C4258 !important',
        '&:hover': {
            color: '#fff !important',
            cursor: 'pointer !important',
            boxShadow: 'none !important',
            backgroundColor: '#4C4258 !important',
        },
    },
    towProgressionParent: {
        background: '#4C4258',
        height: 5,
        flex: 'auto',
        borderRadius: 5,
        marginLeft: '1rem',
        marginRight: '1rem',
    },
    towProgression: {
        borderRadius: 5,
        background: '#018cd7',
    },
    progressSection: {
        display: 'flex',
        alignItems: 'center',
        marginBottom: '1rem',
        marginTop: '1rem',
    },
    levelText: {
        fontSize: 12,
    },
    towContent: {
        display: 'flex',
        marginTop: '10%',
        alignItems: 'center',
        justifyContent: 'center',
    },
    bigText: {
        color: '#4C4258',
        fontSize: '2vh',
        fontWeight: 'bold',
    },
})